#!/usr/bin/env bash

cd driver

echo "[*] Building driver ..."
./gradlew clean assemble

echo "[*] Updating driver stub ..."
unzip app/build/outputs/apk/release/app-release-unsigned.apk -d tmp
cp tmp/classes.dex ../res/driver.dex
rm -Rf tmp

echo "[*] Done."
