#!/usr/bin/env bash

cd driver

echo "[*] Building driver ..."
./gradlew clean fatjar

echo "[*] Updating driver stub ..."
dx --dex --force-jumbo --output=../res/driver.dex build/libs/driver.jar

echo "[*] Done."